name: Trigger auto deployment for albums-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/albums-fe-AutoDeployTrigger-7c1d870f-1ae2-4c33-b0c6-746feeb3f544.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca194ad15957acr.azurecr.io
          username: ${{ secrets.ALBUMSFE_REGISTRY_USERNAME }}
          password: ${{ secrets.ALBUMSFE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca194ad15957acr.azurecr.io/albums-fe:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMSFE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n albums-fe -g reddog1 --server ca194ad15957acr.azurecr.io --username  ${{ secrets.ALBUMSFE_REGISTRY_USERNAME }} --password ${{ secrets.ALBUMSFE_REGISTRY_PASSWORD }}
            az containerapp update -n albums-fe -g reddog1 --image ca194ad15957acr.azurecr.io/albums-fe:${{ github.sha }}
